import React from "react";
import RenderPageContent from "./RenderPageContent";
import { Metadata } from "next";

type Role = "user" | "seller";
export const metadata: Metadata = {
  title: "Paradise Shopping",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/paradise-shopping-logo.png",
  },
};
export default async function page({
  params,
}: {
  params: { role: Role; content: string };
}) {
  const { content, role } = await params;
  return <RenderPageContent role={role} content={content} />;
}
