import type { Metadata } from "next";
import "./globals.css";
import "./product.css";
import "./animation.css";
import { Nunito, Open_Sans } from "next/font/google";
import ReduxProvider from "./ReduxProvider";

import OrderModal from "../components/modal/OrderModal";
import NavBarMobile from "../components/layout/Navbar/NavbarMobile";
import LoadingAnimation from "../components/modal/root/LoadingAnimation";
import SuccessModal from "../components/modal/root/SuccessModal";
import ErrorModal from "../components/modal/root/ErrorModal";
/**
 * Meta data
 */
export const metadata: Metadata = {
  title: "Paradise Shopping",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/electric.webp",
  },
};
/**
 * font famitly
 */
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-nunito",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-open-sans",
});
/**
 * Root layout with all app animation
 * app modal
 * @param param0
 * @returns
 */

type RootLayoutProps = {
  children: React.ReactNode;
};
/**
 * render app
 * @param param0
 * @returns
 */
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${openSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        {/* provider */}
        <ReduxProvider>
          {/* modal */}
          <LoadingAnimation />
          <SuccessModal />
          <NavBarMobile />
          <ErrorModal />
          <OrderModal />
          {/* children */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
