import type { Metadata } from "next";
import "./globals.css";
import "./product.css";
import "./animation.css";
import "../lib/fontawesome";
import ReduxProvider from "./ReduxProvider";
import OrderModal from "@/components/order_modal";
import CheckoutModal from "@/components/checkout/index";
import LoadingAnimation from "@/components/feedback/LoadingAnimation";
import SuccessfullModal from "@/components/feedback/successful";
import ErrorModal from "@/components/feedback/ErrorModal";
import NavigationBarMobileMode from "@/components/web_body/header/sections/NavigationBarMobileMode";
/**
 * Meta data
 */
export const metadata: Metadata = {
  title: "Paradise Shopping paradise of shopping",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/electric.webp",
  },
};
/**
 * Root layout with all app animation
 * app modal
 * @param param0
 * @returns
 */

type RootLayoutProps = {
  children: React.ReactNode;
};
/**
 * render app
 * @param param0
 * @returns
 */
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* provider */}
        <ReduxProvider>
          {/* modal */}
          <LoadingAnimation />
          <SuccessfullModal />
          <NavigationBarMobileMode />
          <ErrorModal />
          <CheckoutModal />
          <OrderModal />
          {/* children */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
