import HomePageWrapper from "./HomePageWrapper";

import HomePage from "../components/product/page/HomePage";
import UserHeader from "../components/layout/Header/Header";
import CarouselHeader from "../components/layout/Carousel/CarouselHeader";
import { Metadata } from "next";
import Footer from "@/components/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Paradise Shopping",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/paradise-shopping-logo.png",
  },
};

export default function Home() {
  return (
    <HomePageWrapper>
      <UserHeader />
      <CarouselHeader />
      <HomePage />
      <Footer />
    </HomePageWrapper>
  );
}
